"""MCP tools — write-up generation (Jinja2), KB synthesis, publish hint."""

from __future__ import annotations

import asyncio
import os
import subprocess
from pathlib import Path
from typing import Any

from jinja2 import Template

from kestrel.mcp import context as mcp_context
from kestrel.mcp import registry
from kestrel.mcp.tools.state import _resolve_session_dir


DEFAULT_TEMPLATE = """# Write-up — {{ machine }}

**OS:** {{ os | default('Unknown') }}  •  **Difficulty:** {{ difficulty | default('Unknown') }}  •  **IP:** {{ ip | default('—') }}

## Summary
{{ sections.get('summary', '_(missing)_') }}

## Recon
{{ sections.get('recon', '_(missing)_') }}

## Foothold
{{ sections.get('foothold', '_(missing)_') }}

## Privilege Escalation
{{ sections.get('privesc', '_(missing)_') }}

## Loot / Flags
- user.txt: `{{ flags.get('user', '—') }}`
- root.txt: `{{ flags.get('root', '—') }}`

## Lessons / Gotchas
{{ sections.get('lessons', '_(missing)_') }}

---
*Generated by Kestrel v{{ kestrel_version }}*
"""


PUBLISH_EMIT_DEFAULT = Path(
    "C:/Proyectos/CobaltoSec/.claude/skills/_shared/publish-prep/emit.py"
)


@registry.tool(
    name="writeup_generate",
    description=(
        "Render a Markdown write-up for `machine` from `sections` + `flags`. Saves to <session_dir>/writeup.md. "
        "sections keys: summary, recon, foothold, privesc, lessons (all optional)."
    ),
    category="writeup",
    input_schema={
        "type": "object",
        "properties": {
            "machine": {"type": "string"},
            "sections": {"type": "object"},
            "flags": {"type": "object"},
            "os": {"type": "string"},
            "difficulty": {"type": "string"},
            "ip": {"type": "string"},
        },
        "required": ["machine"],
    },
)
async def writeup_generate(
    machine: str,
    sections: dict[str, str] | None = None,
    flags: dict[str, str] | None = None,
    os: str | None = None,
    difficulty: str | None = None,
    ip: str | None = None,
) -> dict[str, Any]:
    from kestrel import __version__
    tpl = Template(DEFAULT_TEMPLATE)
    rendered = tpl.render(
        machine=machine,
        sections=sections or {},
        flags=flags or {},
        os=os,
        difficulty=difficulty,
        ip=ip,
        kestrel_version=__version__,
    )
    session_dir = _resolve_session_dir(machine)
    session_dir.mkdir(parents=True, exist_ok=True)
    writeup_path = session_dir / "writeup.md"
    writeup_path.write_text(rendered, encoding="utf-8")
    return {"machine": machine, "writeup_path": str(writeup_path), "byte_count": len(rendered)}


@registry.tool(
    name="writeup_kb_synthesize",
    description=(
        "Synthesize a KB-ingestable markdown from a finished machine's write-up. "
        "Strips spoilers (commands), keeps techniques + CVE refs. Saves to kb/staging/htb-<machine>.md."
    ),
    category="writeup",
)
async def writeup_kb_synthesize(machine: str, kb_staging_dir: str | None = None) -> dict[str, Any]:
    session_dir = _resolve_session_dir(machine)
    writeup_path = session_dir / "writeup.md"
    if not writeup_path.exists():
        return {"error": "writeup_not_found", "expected_path": str(writeup_path)}

    staging = Path(kb_staging_dir or os.environ.get("KESTREL_KB_STAGING", "C:/Proyectos/CobaltoSec/sectors/red-team/kb/staging"))
    staging.mkdir(parents=True, exist_ok=True)
    src_text = writeup_path.read_text(encoding="utf-8")

    # Spoiler stripping: drop ```code blocks``` and inline commands `like this`
    cleaned_lines: list[str] = []
    in_code = False
    for line in src_text.splitlines():
        if line.strip().startswith("```"):
            in_code = not in_code
            cleaned_lines.append("> _(code redacted in KB synthesis)_")
            continue
        if in_code:
            continue
        cleaned_lines.append(line)
    cleaned = "\n".join(cleaned_lines)

    kb_path = staging / f"htb-{machine}.md"
    kb_path.write_text(cleaned, encoding="utf-8")
    return {"machine": machine, "kb_path": str(kb_path), "source": str(writeup_path)}


@registry.tool(
    name="writeup_publish_hint",
    description=(
        "Emit a publish-hint JSON via the shared publish-prep/emit.py helper. "
        "Tells downstream JobSearch automation that a new write-up is ready."
    ),
    category="writeup",
)
async def writeup_publish_hint(machine: str, content_md_path: str | None = None) -> dict[str, Any]:
    emit_script = Path(os.environ.get("KESTREL_PUBLISH_EMIT", str(PUBLISH_EMIT_DEFAULT)))
    if not emit_script.exists():
        return {"error": "emit_script_not_found", "expected_path": str(emit_script)}
    source = content_md_path or str(_resolve_session_dir(machine) / "writeup.md")

    def _do() -> dict[str, Any]:
        proc = subprocess.run(
            [
                "python", str(emit_script),
                "--source", source,
                "--topic", f"htb-{machine}",
                "--kind", "kestrel-writeup",
            ],
            capture_output=True, text=True, timeout=30,
        )
        return {"rc": proc.returncode, "stdout": proc.stdout.strip(), "stderr": proc.stderr.strip()}

    res = await asyncio.to_thread(_do)
    return {"machine": machine, "source": source, **res}
