"""MCP resources — per-session artifacts (intel, recon dir, findings, fingerprint, writeup)."""

from __future__ import annotations

import json
import re
from pathlib import Path

from kestrel.mcp import context as mcp_context
from kestrel.mcp import registry


_SESSION_URI_RE = re.compile(
    r"^kestrel://session/(?P<machine>[^/]+)/(?P<kind>intel|recon|findings|fingerprint|writeup)$"
)


def _machine_session_dir(machine: str) -> Path | None:
    ctx = mcp_context.get_context()
    m = ctx.state_store.get_machine(machine)
    if m and m.session_slug:
        return ctx.session_root / m.session_slug
    return None


def _read_session_file(uri: str, filename: str) -> str:
    match = _SESSION_URI_RE.match(uri)
    if not match:
        return json.dumps({"error": "uri_unparseable", "uri": uri})
    machine = match.group("machine")
    session_dir = _machine_session_dir(machine)
    if session_dir is None:
        return json.dumps({"error": "machine_not_tracked", "machine": machine})
    path = session_dir / filename
    if not path.exists():
        return json.dumps({"error": "artifact_missing", "machine": machine, "path": str(path)})
    return path.read_text(encoding="utf-8")


def _list_session_dir(uri: str, subdir: str) -> str:
    match = _SESSION_URI_RE.match(uri)
    if not match:
        return json.dumps({"error": "uri_unparseable", "uri": uri})
    machine = match.group("machine")
    session_dir = _machine_session_dir(machine)
    if session_dir is None:
        return json.dumps({"error": "machine_not_tracked", "machine": machine})
    dir_path = session_dir / subdir
    if not dir_path.exists():
        return json.dumps({"machine": machine, "subdir": subdir, "files": []})
    entries: list[dict] = []
    for p in sorted(dir_path.rglob("*")):
        if p.is_file():
            entries.append({"path": str(p.relative_to(session_dir)), "size_bytes": p.stat().st_size})
    return json.dumps({"machine": machine, "subdir": subdir, "file_count": len(entries), "files": entries}, indent=2)


@registry.resource(
    uri="kestrel://session/{machine}/intel",
    name="session-intel",
    description="Read <session_dir>/intel.md for the given machine slug.",
    mime_type="text/markdown",
)
async def session_intel(uri: str) -> str:
    return _read_session_file(uri, "intel.md")


@registry.resource(
    uri="kestrel://session/{machine}/findings",
    name="session-findings",
    description="Read <session_dir>/findings.md (live findings notebook).",
    mime_type="text/markdown",
)
async def session_findings(uri: str) -> str:
    return _read_session_file(uri, "findings.md")


@registry.resource(
    uri="kestrel://session/{machine}/writeup",
    name="session-writeup",
    description="Read <session_dir>/writeup.md (generated by writeup_generate).",
    mime_type="text/markdown",
)
async def session_writeup(uri: str) -> str:
    return _read_session_file(uri, "writeup.md")


@registry.resource(
    uri="kestrel://session/{machine}/fingerprint",
    name="session-fingerprint",
    description="Read <session_dir>/fingerprint.json (blind_fingerprint output).",
)
async def session_fingerprint(uri: str) -> str:
    return _read_session_file(uri, "fingerprint.json")


@registry.resource(
    uri="kestrel://session/{machine}/recon",
    name="session-recon",
    description="List files under <session_dir>/recon/ (nmap XMLs, web fingerprints, smb dumps).",
)
async def session_recon(uri: str) -> str:
    return _list_session_dir(uri, "recon")
