#!/usr/bin/env python3
"""Generate docs/tools-reference.md from registered MCP tools/prompts/resources.

Run after Fase 6 to refresh the reference doc:
    python scripts/gen_tools_reference.py
"""

from __future__ import annotations

import os
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# Ensure src/ is importable when run from repo root
ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# Force test-like env so no production state files are touched
os.environ.setdefault("KESTREL_STATE_DIR", str(ROOT / ".cache" / "docgen-state"))
os.environ.setdefault("KESTREL_SESSION_ROOT", str(ROOT / ".cache" / "docgen-sessions"))

from kestrel import __version__
from kestrel.mcp import context as mcp_context
from kestrel.mcp import registry
from kestrel.mcp.server import _load_handler_modules


def main() -> int:
    ctx = mcp_context.ServerContext.from_paths()
    mcp_context.set_context(ctx)
    _load_handler_modules()

    tools = registry.all_tools()
    prompts = registry.all_prompts()
    resources = registry.all_resources()

    by_cat: dict[str, list] = defaultdict(list)
    for t in tools:
        by_cat[t.category].append(t)

    out_lines: list[str] = []
    out_lines.append(f"# Kestrel MCP — Tools Reference (v{__version__})")
    out_lines.append("")
    out_lines.append(f"_Autogenerated {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} by `scripts/gen_tools_reference.py`._")
    out_lines.append("")
    out_lines.append(f"**Totals:** {len(tools)} tools · {len(prompts)} prompts · {len(resources)} resources")
    out_lines.append("")
    out_lines.append("## Index")
    out_lines.append("")
    for cat in sorted(by_cat.keys()):
        out_lines.append(f"- [{cat}](#{cat}) ({len(by_cat[cat])} tool{'s' if len(by_cat[cat]) != 1 else ''})")
    out_lines.append("")
    out_lines.append("---")
    out_lines.append("")

    for cat in sorted(by_cat.keys()):
        out_lines.append(f"## {cat}")
        out_lines.append("")
        for t in sorted(by_cat[cat], key=lambda x: x.name):
            out_lines.append(f"### `{t.name}`")
            out_lines.append("")
            out_lines.append(t.description.strip())
            out_lines.append("")
            schema = t.input_schema
            props = schema.get("properties", {}) if isinstance(schema, dict) else {}
            required = set(schema.get("required", [])) if isinstance(schema, dict) else set()
            if props:
                out_lines.append("**Parameters:**")
                out_lines.append("")
                out_lines.append("| Name | Type | Required | Default |")
                out_lines.append("|------|------|----------|---------|")
                for pname, pdef in props.items():
                    ptype = pdef.get("type", "string") if isinstance(pdef, dict) else "string"
                    pdefault = pdef.get("default", "—") if isinstance(pdef, dict) else "—"
                    req = "✓" if pname in required else " "
                    out_lines.append(f"| `{pname}` | `{ptype}` | {req} | `{pdefault}` |")
                out_lines.append("")
        out_lines.append("---")
        out_lines.append("")

    if prompts:
        out_lines.append("## Prompts")
        out_lines.append("")
        for p in sorted(prompts, key=lambda x: x.name):
            out_lines.append(f"### `{p.name}`")
            out_lines.append("")
            out_lines.append(p.description.strip())
            out_lines.append("")
        out_lines.append("---")
        out_lines.append("")

    if resources:
        out_lines.append("## Resources")
        out_lines.append("")
        out_lines.append("| URI | Name | Description |")
        out_lines.append("|-----|------|-------------|")
        for r in sorted(resources, key=lambda x: x.uri):
            out_lines.append(f"| `{r.uri}` | {r.name} | {r.description.strip()} |")
        out_lines.append("")

    docs_dir = ROOT / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    target = docs_dir / "tools-reference.md"
    target.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {target} ({len(tools)} tools, {len(prompts)} prompts, {len(resources)} resources)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
